//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    [NonPersistent]
    public partial class XPOBase : XPObject
    {
        DateTime fDateCreated;
        public DateTime DateCreated
        {
            get { return fDateCreated; }
            set { SetPropertyValue<DateTime>(nameof(DateCreated), ref fDateCreated, value); }
        }
        DateTime fDateModified;
        public DateTime DateModified
        {
            get { return fDateModified; }
            set { SetPropertyValue<DateTime>(nameof(DateModified), ref fDateModified, value); }
        }
        string fUserCreated;
        public string UserCreated
        {
            get { return fUserCreated; }
            set { SetPropertyValue<string>(nameof(UserCreated), ref fUserCreated, value); }
        }
        string fIPAddress;
        public string IPAddress
        {
            get { return fIPAddress; }
            set { SetPropertyValue<string>(nameof(IPAddress), ref fIPAddress, value); }
        }
    }

}
