//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOColConference : XPObject
    {
        string fCodeID;
        [Indexed(Name = @"IDXCodeID")]
        [Size(60)]
        public string CodeID
        {
            get { return fCodeID; }
            set { SetPropertyValue<string>(nameof(CodeID), ref fCodeID, value); }
        }
        string fConferenceName;
        [Size(60)]
        public string ConferenceName
        {
            get { return fConferenceName; }
            set { SetPropertyValue<string>(nameof(ConferenceName), ref fConferenceName, value); }
        }
        XPOColConfGroup fGroupID;
        [Association(@"XPOCollConferencesReferencesXPOColConfGroup")]
        public XPOColConfGroup GroupID
        {
            get { return fGroupID; }
            set { SetPropertyValue<XPOColConfGroup>(nameof(GroupID), ref fGroupID, value); }
        }
        [Association(@"XPOColConfDivReferencesXPOCollConferences")]
        public XPCollection<XPOColConfDiv> XPOColConfDivs { get { return GetCollection<XPOColConfDiv>(nameof(XPOColConfDivs)); } }
        [Association(@"XPOCollegeTeamReferencesXPOColConference")]
        public XPCollection<XPOCollegeTeam> XPOCollegeTeams { get { return GetCollection<XPOCollegeTeam>(nameof(XPOCollegeTeams)); } }
    }

}
