//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOCollegeTeam : XPObject
    {
        string fTeamName;
        [Size(50)]
        public string TeamName
        {
            get { return fTeamName; }
            set { SetPropertyValue<string>(nameof(TeamName), ref fTeamName, value); }
        }
        XPOFacility fFacility;
        [Association(@"XPOTeamReferencesXPOFacility")]
        public XPOFacility Facility
        {
            get { return fFacility; }
            set { SetPropertyValue<XPOFacility>(nameof(Facility), ref fFacility, value); }
        }
        XPOSportsCode fSportCode;
        [Association(@"XPOTeamReferencesXPOAllSports")]
        public XPOSportsCode SportCode
        {
            get { return fSportCode; }
            set { SetPropertyValue<XPOSportsCode>(nameof(SportCode), ref fSportCode, value); }
        }
        XPOUniversity fOwner;
        [Association(@"XPOCollegeTeamReferencesXPOUniversity")]
        public XPOUniversity Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<XPOUniversity>(nameof(Owner), ref fOwner, value); }
        }
        string fPicture;
        [Size(250)]
        public string Picture
        {
            get { return fPicture; }
            set { SetPropertyValue<string>(nameof(Picture), ref fPicture, value); }
        }
        string fLogo;
        [Size(250)]
        public string Logo
        {
            get { return fLogo; }
            set { SetPropertyValue<string>(nameof(Logo), ref fLogo, value); }
        }
        XPOColConference fConference;
        [Association(@"XPOCollegeTeamReferencesXPOColConference")]
        public XPOColConference Conference
        {
            get { return fConference; }
            set { SetPropertyValue<XPOColConference>(nameof(Conference), ref fConference, value); }
        }
    }

}
