//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    /// <summary>
    /// College conference Groups
    /// </summary>
    public partial class XPOColConfGroup : XPObject
    {
        string fGroupID;
        [Indexed(Name = @"IDXGroupID")]
        [Size(6)]
        public string GroupID
        {
            get { return fGroupID; }
            set { SetPropertyValue<string>(nameof(GroupID), ref fGroupID, value); }
        }
        string fGroupName;
        [Size(60)]
        public string GroupName
        {
            get { return fGroupName; }
            set { SetPropertyValue<string>(nameof(GroupName), ref fGroupName, value); }
        }
        [Association(@"XPOCollConferencesReferencesXPOColConfGroup")]
        public XPCollection<XPOColConference> XPOCollConferencesCollection { get { return GetCollection<XPOColConference>(nameof(XPOCollConferencesCollection)); } }
    }

}
