//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOFBReferee : XPObject
    {
        int fRefereeID;
        public int RefereeID
        {
            get { return fRefereeID; }
            set { SetPropertyValue<int>(nameof(RefereeID), ref fRefereeID, value); }
        }
        string fDescription;
        [Size(30)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fFieldPosition;
        public string FieldPosition
        {
            get { return fFieldPosition; }
            set { SetPropertyValue<string>(nameof(FieldPosition), ref fFieldPosition, value); }
        }
        string fResponsibilities;
        public string Responsibilities
        {
            get { return fResponsibilities; }
            set { SetPropertyValue<string>(nameof(Responsibilities), ref fResponsibilities, value); }
        }
        string fRunPlays;
        public string RunPlays
        {
            get { return fRunPlays; }
            set { SetPropertyValue<string>(nameof(RunPlays), ref fRunPlays, value); }
        }
        string fPassPlays;
        public string PassPlays
        {
            get { return fPassPlays; }
            set { SetPropertyValue<string>(nameof(PassPlays), ref fPassPlays, value); }
        }
        string fSpecialTeams;
        public string SpecialTeams
        {
            get { return fSpecialTeams; }
            set { SetPropertyValue<string>(nameof(SpecialTeams), ref fSpecialTeams, value); }
        }
        XPOParticipant fParticipants;
        [Association(@"XPORefereeFootballReferencesXPOParticipants")]
        public XPOParticipant Participants
        {
            get { return fParticipants; }
            set { SetPropertyValue<XPOParticipant>(nameof(Participants), ref fParticipants, value); }
        }
    }

}
