//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    /// <summary>
    /// Football Coach
    /// </summary>
    public partial class XPOFBCoach : XPObject
    {
        string fCoachID;
        public string CoachID
        {
            get { return fCoachID; }
            set { SetPropertyValue<string>(nameof(CoachID), ref fCoachID, value); }
        }
        string fDescription;
        [Size(30)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fResposibilities;
        public string Resposibilities
        {
            get { return fResposibilities; }
            set { SetPropertyValue<string>(nameof(Resposibilities), ref fResposibilities, value); }
        }
        string fPersonCategoryID;
        public string PersonCategoryID
        {
            get { return fPersonCategoryID; }
            set { SetPropertyValue<string>(nameof(PersonCategoryID), ref fPersonCategoryID, value); }
        }
        XPOParticipant fParticipants;
        [Association(@"XPOFootballCoachReferencesXPOParticipants")]
        public XPOParticipant Participants
        {
            get { return fParticipants; }
            set { SetPropertyValue<XPOParticipant>(nameof(Participants), ref fParticipants, value); }
        }
    }

}
