//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOMunicipality : XPObject
    {
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fAddress;
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fInformation;
        [Size(4096)]
        public string Information
        {
            get { return fInformation; }
            set { SetPropertyValue<string>(nameof(Information), ref fInformation, value); }
        }
        [Association(@"XPOProTeamReferencesXPOMunicipality")]
        public XPCollection<XPOProTeam> XPOProTeams { get { return GetCollection<XPOProTeam>(nameof(XPOProTeams)); } }
    }

}
