//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOProTeam : XPObject
    {
        string fTeamName;
        [Size(50)]
        public string TeamName
        {
            get { return fTeamName; }
            set { SetPropertyValue<string>(nameof(TeamName), ref fTeamName, value); }
        }
        XPOFacility fFacility;
        [Association(@"XPOProTeamReferencesXPOFacility")]
        public XPOFacility Facility
        {
            get { return fFacility; }
            set { SetPropertyValue<XPOFacility>(nameof(Facility), ref fFacility, value); }
        }
        XPOSportsCode fSportsCode;
        [Association(@"XPOProTeamReferencesXPOSportsCode")]
        public XPOSportsCode SportsCode
        {
            get { return fSportsCode; }
            set { SetPropertyValue<XPOSportsCode>(nameof(SportsCode), ref fSportsCode, value); }
        }
        XPOMunicipality fOwner;
        [Association(@"XPOProTeamReferencesXPOMunicipality")]
        public XPOMunicipality Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<XPOMunicipality>(nameof(Owner), ref fOwner, value); }
        }
        string fPicture;
        [Size(250)]
        public string Picture
        {
            get { return fPicture; }
            set { SetPropertyValue<string>(nameof(Picture), ref fPicture, value); }
        }
        string fLogo;
        [Size(250)]
        public string Logo
        {
            get { return fLogo; }
            set { SetPropertyValue<string>(nameof(Logo), ref fLogo, value); }
        }
    }

}
