//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOProFranchise : XPObject
    {
        string fFranchise;
        public string Franchise
        {
            get { return fFranchise; }
            set { SetPropertyValue<string>(nameof(Franchise), ref fFranchise, value); }
        }
        string fDivision;
        public string Division
        {
            get { return fDivision; }
            set { SetPropertyValue<string>(nameof(Division), ref fDivision, value); }
        }
        string fSport;
        public string Sport
        {
            get { return fSport; }
            set { SetPropertyValue<string>(nameof(Sport), ref fSport, value); }
        }
        string fTags;
        public string Tags
        {
            get { return fTags; }
            set { SetPropertyValue<string>(nameof(Tags), ref fTags, value); }
        }
        [Association(@"XPOProFacilityReferencesXPOFranchise")]
        public XPCollection<XPOProFacility> XPOProFacilities { get { return GetCollection<XPOProFacility>(nameof(XPOProFacilities)); } }
    }

}
