//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOPlayers : XPObject
    {
        XPOPerson fPerson;
        [Association(@"XPOPlayersReferencesXPOPerson")]
        public XPOPerson Person
        {
            get { return fPerson; }
            set { SetPropertyValue<XPOPerson>(nameof(Person), ref fPerson, value); }
        }
        string fNumber;
        public string Number
        {
            get { return fNumber; }
            set { SetPropertyValue<string>(nameof(Number), ref fNumber, value); }
        }
    }

}
