//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOProFacility : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fCapacity;
        public string Capacity
        {
            get { return fCapacity; }
            set { SetPropertyValue<string>(nameof(Capacity), ref fCapacity, value); }
        }
        string fLat;
        public string Lat
        {
            get { return fLat; }
            set { SetPropertyValue<string>(nameof(Lat), ref fLat, value); }
        }
        string fLon;
        public string Lon
        {
            get { return fLon; }
            set { SetPropertyValue<string>(nameof(Lon), ref fLon, value); }
        }
        XPOProFranchise fFranchise;
        [Association(@"XPOProFacilityReferencesXPOFranchise")]
        public XPOProFranchise Franchise
        {
            get { return fFranchise; }
            set { SetPropertyValue<XPOProFranchise>(nameof(Franchise), ref fFranchise, value); }
        }
    }

}
