//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOParticipant : XPObject
    {
        string fPersonCategoryID;
        [Size(10)]
        public string PersonCategoryID
        {
            get { return fPersonCategoryID; }
            set { SetPropertyValue<string>(nameof(PersonCategoryID), ref fPersonCategoryID, value); }
        }
        string fRole;
        [Size(30)]
        public string Role
        {
            get { return fRole; }
            set { SetPropertyValue<string>(nameof(Role), ref fRole, value); }
        }
        string fDescription;
        [Size(1024)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        [Association(@"XPOPlayerFootballReferencesXPOParticipants")]
        public XPCollection<XPOPlayer> XPOPlayerFootballs { get { return GetCollection<XPOPlayer>(nameof(XPOPlayerFootballs)); } }
        [Association(@"XPORefereeFootballReferencesXPOParticipants")]
        public XPCollection<XPOFBReferee> XPORefereeFootballs { get { return GetCollection<XPOFBReferee>(nameof(XPORefereeFootballs)); } }
        [Association(@"XPOFootballCoachReferencesXPOParticipants")]
        public XPCollection<XPOFBCoach> XPOFootballCoaches { get { return GetCollection<XPOFBCoach>(nameof(XPOFootballCoaches)); } }
    }

}
