//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOPerson : XPOBase
    {
        string fFirstName;
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fLastName;
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        XPOAddress fAddress;
        public XPOAddress Address
        {
            get { return fAddress; }
            set { SetPropertyValue<XPOAddress>(nameof(Address), ref fAddress, value); }
        }
        [Association(@"XPOAddressReferencesXPOPerson")]
        public XPCollection<XPOAddress> XPOAddresses { get { return GetCollection<XPOAddress>(nameof(XPOAddresses)); } }
        [Association(@"XPOPlayersReferencesXPOPerson")]
        public XPCollection<XPOPlayers> XPOPlayersCollection { get { return GetCollection<XPOPlayers>(nameof(XPOPlayersCollection)); } }
    }

}
