//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    /// <summary>
    /// Staff administrating this sport
    /// </summary>
    public partial class XPOStaff : XPObject
    {
        string fSport;
        public string Sport
        {
            get { return fSport; }
            set { SetPropertyValue<string>(nameof(Sport), ref fSport, value); }
        }
        string fUniversity;
        public string University
        {
            get { return fUniversity; }
            set { SetPropertyValue<string>(nameof(University), ref fUniversity, value); }
        }
        string fPerson;
        public string Person
        {
            get { return fPerson; }
            set { SetPropertyValue<string>(nameof(Person), ref fPerson, value); }
        }
        XPOStaffTitle fTitle;
        [Association(@"XPOStaffReferencesXPOStaffTitle")]
        public XPOStaffTitle Title
        {
            get { return fTitle; }
            set { SetPropertyValue<XPOStaffTitle>(nameof(Title), ref fTitle, value); }
        }
    }

}
