//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOState : XPObject
    {
        string fState;
        [Indexed(Name = @"idxState", Unique = true)]
        public string State
        {
            get { return fState; }
            set { SetPropertyValue<string>(nameof(State), ref fState, value); }
        }
        [Association(@"XPOAddressReferencesXPOState")]
        public XPCollection<XPOAddress> XPOAddresses { get { return GetCollection<XPOAddress>(nameof(XPOAddresses)); } }
    }

}
