//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOSportsCode : XPObject
    {
        string fSportCode;
        [Indexed(Name = @"IDXSportCode")]
        [Size(10)]
        public string SportCode
        {
            get { return fSportCode; }
            set { SetPropertyValue<string>(nameof(SportCode), ref fSportCode, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        XPOSportType fSportType;
        [Association(@"XPOAllSportsReferencesXPOSportType")]
        public XPOSportType SportType
        {
            get { return fSportType; }
            set { SetPropertyValue<XPOSportType>(nameof(SportType), ref fSportType, value); }
        }
        [Association(@"XPOTeamReferencesXPOAllSports")]
        public XPCollection<XPOCollegeTeam> XPOTeams { get { return GetCollection<XPOCollegeTeam>(nameof(XPOTeams)); } }
        [Association(@"XPOProTeamReferencesXPOSportsCode")]
        public XPCollection<XPOProTeam> XPOProTeams { get { return GetCollection<XPOProTeam>(nameof(XPOProTeams)); } }
    }

}
