//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOTeamByYear : XPObject
    {
        string fYear;
        public string Year
        {
            get { return fYear; }
            set { SetPropertyValue<string>(nameof(Year), ref fYear, value); }
        }
        string fWins;
        public string Wins
        {
            get { return fWins; }
            set { SetPropertyValue<string>(nameof(Wins), ref fWins, value); }
        }
        string fLosses;
        public string Losses
        {
            get { return fLosses; }
            set { SetPropertyValue<string>(nameof(Losses), ref fLosses, value); }
        }
        string fTeam;
        public string Team
        {
            get { return fTeam; }
            set { SetPropertyValue<string>(nameof(Team), ref fTeam, value); }
        }
    }

}
