//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOTeamTypeTag : XPObject
    {
        string fTeamType;
        [Size(50)]
        public string TeamType
        {
            get { return fTeamType; }
            set { SetPropertyValue<string>(nameof(TeamType), ref fTeamType, value); }
        }
        string fDescription;
        [Size(254)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        [Association(@"XPOTeamReferencesXPOTeamTypeTag")]
        public XPCollection<XPOTeam> XPOTeams { get { return GetCollection<XPOTeam>(nameof(XPOTeams)); } }
    }

}
