//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOUnivBasketBall : XPObject
    {
        string ftemp;
        public string temp
        {
            get { return ftemp; }
            set { SetPropertyValue<string>(nameof(temp), ref ftemp, value); }
        }
    }

}
