//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOUnivFootball : XPObject
    {
        string fSurfaceTag;
        public string SurfaceTag
        {
            get { return fSurfaceTag; }
            set { SetPropertyValue<string>(nameof(SurfaceTag), ref fSurfaceTag, value); }
        }
    }

}
