//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace OSModel.OSDB
{

    public partial class XPOUniversity : XPObject
    {
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        XPOAddress fAddress;
        public XPOAddress Address
        {
            get { return fAddress; }
            set { SetPropertyValue<XPOAddress>(nameof(Address), ref fAddress, value); }
        }
        string fInformation;
        [Size(4096)]
        public string Information
        {
            get { return fInformation; }
            set { SetPropertyValue<string>(nameof(Information), ref fInformation, value); }
        }
        string fPicture;
        [Size(50)]
        public string Picture
        {
            get { return fPicture; }
            set { SetPropertyValue<string>(nameof(Picture), ref fPicture, value); }
        }
        string fLogo;
        [Size(200)]
        public string Logo
        {
            get { return fLogo; }
            set { SetPropertyValue<string>(nameof(Logo), ref fLogo, value); }
        }
        int fRecNO;
        public int RecNO
        {
            get { return fRecNO; }
            set { SetPropertyValue<int>(nameof(RecNO), ref fRecNO, value); }
        }
        XPOColConfDiv fDivID;
        /// <summary>
        /// Division ID
        /// </summary>
        [Association(@"XPOUniversityReferencesXPOColConfDiv")]
        public XPOColConfDiv DivID
        {
            get { return fDivID; }
            set { SetPropertyValue<XPOColConfDiv>(nameof(DivID), ref fDivID, value); }
        }
        int fTeamColor1;
        public int TeamColor1
        {
            get { return fTeamColor1; }
            set { SetPropertyValue<int>(nameof(TeamColor1), ref fTeamColor1, value); }
        }
        int fTeamColor2;
        public int TeamColor2
        {
            get { return fTeamColor2; }
            set { SetPropertyValue<int>(nameof(TeamColor2), ref fTeamColor2, value); }
        }
        [Association(@"XPOCollegeTeamReferencesXPOUniversity")]
        public XPCollection<XPOCollegeTeam> XPOCollegeTeams { get { return GetCollection<XPOCollegeTeam>(nameof(XPOCollegeTeams)); } }
    }

}
